replicaCount: 1
image:
  repository: jusi13/ai-model-api
  tag: main-8
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 80
ingress:
  enabled: false
  host: ai-model.local
  annotations: {}
  tls: []
resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi
minio:
  endpoint: "http://minio.minio.svc.cluster.local:9000"
  bucket: "models"
  accessKeySecret: "minio-app-secret"
  secretKeySecret: "minio-app-secret"
modelDir: "/tmp/model"
env:
  PYTHONUNBUFFERED: "1"
  PYTHONDONTWRITEBYTECODE: "1"
