image:
  repository: jusi13/ai-dataset
  tag: latest

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 512Mi

env:
  MINIO_ENDPOINT: "http://localhost:32000"
  MINIO_SECRET_NAME: "minio-app-secret"
  # MINIO_ACCESS_KEY_NAME: "accessKey"
  # MINIO_SECRET_KEY_NAME: "secretKey"

restartPolicy: Never
backoffLimit: 2
