image:
  repository: jusi13/ai-dataset
  tag: latest

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 512Mi

env:
  - name: MINIO_ENDPOINT
    value: "http://localhost:32000"
  - name: MINIO_ACCESS_KEY
    valueFrom:
      secretKeyRef:
        name: minio-app-secret
        key: accessKey
  - name: MINIO_SECRET_KEY
    valueFrom:
      secretKeyRef:
        name: minio-app-secret
        key: secretKey

restartPolicy: Never
backoffLimit: 2

