image:
  repository: jusi13/ai-dataset
  tag: latest

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 512Mi

env:
  MINIO_ENDPOINT: "http://localhost:32000"

restartPolicy: Never
backoffLimit: 2

