apiVersion: v2
name: minio
description: MinIO deployment managed by ArgoCD
type: application
version: 0.1.0
appVersion: "1.0"
dependencies:
  - name: minio
    version: 5.0.14
    repository: https://charts.min.io/