minio:
  mode: standalone
  replicas: 1
  existingSecret: minio-secret

  users:
    - secretRef: minio-app-secret
      policy: readwrite

  persistence:
    enabled: true
    size: 5Gi
    storageClass: local-path
  service:
    type: NodePort
    nodePorts:
      api: 30090
      console: 30091
  buckets:
    - name: ebooks
      policy: none
      purge: false
  resources:
    requests:
      memory: 512Mi
      cpu: 250m
    limits:
      memory: 512Mi
      cpu: 500m